# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_comentario', models.CharField(max_length=50)),
                ('puntuacion', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_genero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('creador', models.CharField(max_length=50)),
                ('comentario', models.ManyToManyField(to='webjuego.Comentario')),
                ('genero', models.ManyToManyField(to='webjuego.Genero')),
            ],
        ),
    ]
