# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webjuego', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrocinador', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('gmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='nomb_comentario',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='genero',
            old_name='nomb_genero',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='puntuacion',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='comentario',
        ),
        migrations.AddField(
            model_name='juego',
            name='comentario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webjuego.Comentario'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='creador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webjuego.Creador'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='genero',
            field=models.ManyToManyField(default=0, to='webjuego.Genero'),
        ),
        migrations.CreateModel(
            name='Puntuacione',
            fields=[
                ('valoracion', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webjuego.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webjuego.Usuario'),
        ),
        migrations.AddField(
            model_name='juego',
            name='puntuacione',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webjuego.Puntuacione'),
        ),
    ]
