# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjuego', '0003_auto_20171003_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plataforma',
            name='juego',
        ),
        migrations.AddField(
            model_name='juego',
            name='plataforma',
            field=models.ManyToManyField(default=0, to='webjuego.Plataforma'),
        ),
    ]
