# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjuego', '0004_auto_20171003_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='plataforma',
        ),
        migrations.AddField(
            model_name='plataforma',
            name='juego',
            field=models.ManyToManyField(default=0, to='webjuego.Juego'),
        ),
    ]
