# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webjuego', '0006_auto_20171023_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='avatar',
        ),
    ]
